services:
  app:
    build:
      context: .
      target: dev
    image: todo-app:development
    volumes:
      - .:/app
    ports:
      - 8000:8000
    # env_file:
    #   - .env
    environment:
      DB_USER: ${POSTGRES_USER}
      DEV_DATABASE: ${POSTGRES_DATABASE}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg-dev-data:/var/lib/postgresql/data
    # env_file:
    #   - .env
    # environment:
    #   POSTGRES_USER: $DB_USER
    #   POSTGRES_DB: $DEV_DATABASE
    #   POSTGRES_PASSWORD: $DB_PASSWORD

volumes:
  pg-dev-data:
