services:
  app:
    build:
      context: .
      target: dev
    image: todo-app:development
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - pg-dev-data:/var/lib/postgresql/data
    # env_file:
    #   - .env
    # environment:
    #   POSTGRES_USER: $DB_USER
    #   POSTGRES_DB: $DEV_DATABASE
    #   POSTGRES_PASSWORD: $DB_PASSWORD

volumes:
  pg-dev-data:
