name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: shrujana
          POSTGRES_DB: wd-todo-test
        ports:
          - 5432:5432
        options: >
          --health-cmd="pg_isready -U postgres" 
          --health-interval=10s 
          --health-timeout=5s

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-app-test .

      - name: Wait for PostgreSQL to be ready
        run: until docker run --network=host --rm my-app-test pg_isready -h 127.0.0.1 -p 5432 -U postgres; do echo "Waiting for postgres..."; sleep 1; done

      - name: Run Jest tests in Docker
        run: docker run --network=host --rm my-app-test
