services:
  app:
    build:
      context: .
      target: dev
    image: todo-app:development
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: ["./wait-for-it.sh", "db:5432", "--", "npm", "test"]
    # env_file:
    #   - .env
    environment:
      DB_USER: $${{ secrets.DB_USER }}
      DEV_DATABASE: $${{ secrets.DEV_DATABASE }}
      DB_PASSWORD: $${{ secrets.DB_PASSWORD }}
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg-dev-data:/var/lib/postgresql/data
    environment:
      DB_USER: $${{ secrets.DB_USER }}
      DEV_DATABASE: $${{ secrets.DEV_DATABASE }}
      DB_PASSWORD: $${{ secrets.DB_PASSWORD }}
    # env_file:
    #   - .env
    # environment:
    #   POSTGRES_USER: $DB_USER
    #   POSTGRES_DB: $DEV_DATABASE
    #   POSTGRES_PASSWORD: $DB_PASSWORD

volumes:
  pg-dev-data:
